services:
  backend:
    build: ./mern/backend
    ports:
      - "5050:5050" 
    networks:
      - demo
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase  
    depends_on:
      - mongodb

  frontend:
    build: ./mern/frontend
    ports:
      - "5173:5173"  
    networks:
      - demo
    environment:
      REACT_APP_API_URL: http://backend:5050 

  mongodb:
    image: mongo:latest  
    ports:
      - "27017:27017"  
    networks:
      - demo
    volumes:
      - mongo-data:/data/db  

networks:
  demo:
    driver: bridge 

volumes:
  mongo-data:
    driver: local  # Persist MongoDB data locally

